# Site settings
title: Drndic Lab
email: drndic@physics.upenn.edu
description: "Drndic Lab at the University of Pennsylvania."
baseurl: ""
url: "http://www.physics.upenn.edu/drndicgroup/"
github_username:  parkin

# Build settings
markdown: kramdown
permalink: pretty
