# Site settings
title: Drndi&#263 Lab
pi: Marija Drndi&#263
email: drndic@physics.upenn.edu
description: "Drndi&#263 Lab at the University of Pennsylvania."
baseurl: ""
url: "http://www.physics.upenn.edu/drndicgroup/"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [scss, node_modules, .bowerrc, bower.json, package.json, Gruntfile.js, test]
